export enum TagType {
  SUB_CATEGORY = 'SUB_CATEGORY',
  EXERCISE = 'EXERCISE',
  TARGET_AREA = 'TARGET_AREA',
  MOVEMENT_PATTERN = 'MOVEMENT_PATTERN',
}

export enum CategoryEnum {
  STRENGTH = 'STRENGTH',
  CARDIO = 'CARDIO',
  FUNCTION = 'FUNCTION',
  MOBILE = 'MOBILE',
  LIFESTYLE = 'LIFESTYLE',
}
