export enum TestInputTypeEnum {
  ONE_RM = 'ONE_RM',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  REPS = 'REPS',
  DISTANCE = 'DISTANCE',
  TIME = 'TIME',
  WEIGHT = 'WEIGHT',
  RATIO = 'RATIO',
  RELATIVE_PROFILE = 'RELATIVE_PROFILE',
  CUSTOM_NUMERIC = 'CUSTOM_NUMERIC',
}
